### ISSUE TITLE
Andre kilde-språk

### ISSUE THREAD

**Issue by espensj** [dohliam/gasp-translator#1] opened 2015-10-13 17:17 UTC
Jeg savner muligheten til å velge et annet språk enn engelsk som kildespråk (det er lettere å oversette fra bokmål til svensk enn fra engelsk).

**Comment by dohliam** [comment] 2015-10-13 17:46
Good idea, but the problem is that there is a much smaller pool of Norwegian stories at the moment, so you would only be able to work with the 16 or so stories that have been translated already. It would be much easier to make versions for translating from Afrikaans (244 stories), Kiswahili (126), isiZulu (109), French (103), or Luganda (103), which are the top languages with the most stories in ASP at the moment.

As the number of translated stories in Global-ASP grows, it will make much more sense to incorporate this as part of the translation system. For now, you can still translate directly from Norwegian to Swedish using the .md files in the Global-ASP repo. :smile:

**Comment by dohliam** [comment] 2016-05-06 11:17
Closing this issue since there has been a [Global-ASP oversetter på norsk](http://global-asp.github.io/experiments/gt-no/) available for some time now.

**Closed as completed by dohliam** 2016-05-06 11:17 UTC
Labels: enhancement
